config/routes.rb
Rails.application.routes.draw do

  root "welcome#index"
  get 'sign-up', to: 'registration#new'
  post 'sign-up', to: 'registration#create'
  get 'sign-in', to: 'authentication#new'
  post 'sign-in', to: 'authentication#create'

  resources :users do
    resources :posts
    resources :categories
  end

  resources :categories do
    resources :posts 
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :posts
  has_many :users, through: :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :posts
  has_many :categories, through: :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    if session[:user_id].present?
      @user=User.find(session[:user_id])
    end
  end
end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
      flash[:notice] = "Welcome #{user.email}"
    else
      render :new
    end
  end



end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_and_set_user
  before_action :set_post, only: [:show, :update]

  def new
    @post = @user.posts.new
  end

  def index
    @posts = @user.posts.all
  end


  def create
    @post = @user.posts.new(post_params)
    if @post.save
      flash[:notice] = "Post has been created"
      redirect_to user_posts_path(@user)
    else
      render :new
    end
  end

  def show
  end

  def update
    if @post.update(post_params)
      redirect_to user_post_path(@user,@post), notice: "Post has been successfully updated"
    else
      redirect_to user_post_path(@user,@post)
    end
  end

  private

  def find_and_set_user
    @user = User.find(params[:user_id])
  end

  def post_params
    params.require(:post).permit(:title, :content, :user_id, :category_id)
  end

  def set_post
    @post=Post.find(params[:id])
  end




end

app/controllers/registration_controller.rb
class RegistrationController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authentication/new.html.erb
Sign In

<%= form_tag sign_in_path %>

<%= label_tag :email %>
<%= email_field_tag :email %>

<%= label_tag :password %>
<%= password_field_tag :password %>

<%= submit_tag "Sign In" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlogApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= yield %>

</body>
</html>

app/views/posts/index.html.erb
List of User Posts

<%= link_to "New Post", new_user_post_path(@user) %>

<% @user.posts.each do |post|%>


<%= link_to post.title, user_post_path(@user, post) %>
<%= post.content %>

<% end %>

app/views/posts/new.html.erb
New Post

<%= form_for [@user, @post] do |f| %>

<%= f.label :title %>
<%= f.text_field :title %>

<%= f.label :content %>
<%= f.text_area :content %>

<%= f.submit  %>

<% end %>

app/views/posts/show.html.erb
<%= @post.title %>
<%= @post.content %>

<%= notice %>


<%= form_for [@user, @post] do |f| %>
<%= f.label :category_id, "Category" %>
<%= f.collection_select(:category_id, Category.all, :id, :title, {include_blank: "Please select category"}) %>
<%= f.submit "Update" %>
<% end %>

app/views/welcome/index.html.erb
<%= link_to "Sign Up", sign_up_path %>
<%= link_to "Sign In", sign_in_path %>
<% if current_user %>
  <%= link_to "Posts", user_posts_path(current_user) %>
<% end %>
<% if flash[:notice] %>
<%= flash[:notice] %>
<% end %>